services:
  - type: web
    name: telegram-network-scanner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token-here
      - key: OWNER_CHAT_ID
        value: your-telegram-chat-id-here