services:
  - type: web
    name: telegram-network-scanner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: OWNER_CHAT_ID
        value: your_chat_id_here
